### ISSUE TITLE
Integrating features from rust_sodium

### ISSUE THREAD

**Issue by dbrgn** [sodiumoxide/sodiumoxide#192] opened 2018-01-29 12:38 UTC
There is an alternative libsodium wrapper maintained by Maidsafe: https://github.com/maidsafe/rust_sodium

One of the main differences is that it downloads libsodium during the build process and builds it statically. This makes it much easier to build for different targets, e.g. iOS. It also does CI on all three major opeating systems.

I'm not sure whether the Maidsafe developers got in contact with you before they forked sodiumoxide. Would you be open to integrate changes like these (plus cross platform support + CI) into sodiumoxide directly? Static builds could be put behind a feature flag. I think the community would benefit from less fragmentation in this regard.

**Comment by dnaq** [comment] 2018-01-29 12:54
Hi, I'm aware that they have forked sodium oxide, but they haven't asked me to upstream their fork yet.

I agree that downloading libsodium during installation is a nice feature, but it would also require that we keep a list of known hashes of current libsodium versions in the sodiumoxide repository so that we can make sure that the downloaded libsodium is a real one before installing (or throw security out the window by just downloading a tarball and installing it, which seems a bit reckless for something that calls itself a secure cryptographic library).

This creates an unfortunate maintenance burden on sodiumoxide. Maybe a compromise were it's possible to manually download a version of libsodium and give the path to the library as an environment variable?

I'm currently undecided on what would be the best way forward.

**Comment by dbrgn** [comment] 2018-01-29 13:09
> or throw security out the window by just downloading a tarball and installing it

I fully agree :) I opened an issue for that: https://github.com/maidsafe/rust_sodium/issues/45

> but it would also require that we keep a list of known hashes of current libsodium versions in the sodiumoxide repository

Not necessarily, since libsodium provides GPG and minisig signatures. (Verifying minisig is a bit of a chicken-and-egg since it requires libsodium, but we could probably find a way to verify one of those two signatures without too much hassle.)

> This creates an unfortunate maintenance burden on sodiumoxide

I think the verification thing wouldn't add much of a maintenance burden. A signature signing pubkey only needs to be added once. And even if that isn't a viable approach: The download URL needs to be updated for new releases anyways, in that case it's simple to also update the associated SHA256 (or whatever) hash.

The bigger maintenance burden would be to ensure compatibility with all major operating systems (ideally including cross compilation for Android / iOS), but I think that's something that should be supported in any case (especially since Rust makes it quite easy).

**Comment by dbrgn** [comment] 2018-01-29 13:12
(By the way, the current `rust_sodium_sys` build script is quite hacky, but could be further cleaned up. The pending pull requests already to that partially. So don't take that as reference.)

**Comment by dbrgn** [comment] 2018-02-07 10:37
Would @Fraser999 be interested in upstreaming the changes? I would be willing to help. The libsodium-in-Rust ecosystem could benefit from a single go-to solution.

**Comment by Fraser999** [comment] 2018-02-07 11:37
I agree that a single Rust wrapper in crates.io would be good, however the two projects have diverged in a few areas as mentioned in the OP.  We were originally submitting PRs here, but created our own fork (well... not fork because we needed to publish something to crates) primarily due to #135.  Since then the further changes we've made in order of most-important to least are:
* exposed the ability to initialise libsodium with a psuedorandom number generator, allowing for reproducible data to be generated, which can be useful in the context of tests
* added tests to ensure the FFI bindings match the native library's interface
* run CI tests on Windows (AppVeyor), OS X and Linux (Travis)
* heavily modified the source code to match our style guide (mostly default rustfmt standards and warning-free clippy)

I'd be happy to try and collaborate on resolving these differences to allow us to deprecate rust_sodium in favour of sodiumoxide, but I have fairly limited time and my first priority would be to resolve outstanding issues in rust_sodium.

**Comment by dbrgn** [comment] 2018-02-07 11:56
sodiumoxide would benefit from 2 and 3. The first change could be added maybe behind a feature flag? And applying rustfmt and clippy to the codebase wouldn't hurt either.

But that's probably something that @dnaq would have to decide 🙂

**Comment by Fraser999** [comment] 2018-02-07 12:12
Yup, the feature flag for point 1 would be fine I'm sure.  Would probably be a good thing to have disabled by default anyway (https://www.privateinternetaccess.com/blog/2017/08/libsodium-v1-0-12-and-v1-0-13-security-assessment/#section_3_5_4).

As for rustfmt and clippy, I think clippy is by far the more useful, but dropping these probably wouldn't be a blocker for us.

**Comment by dnaq** [comment] 2018-02-15 13:52
I'm ok with both rustfmt and clippy changes, none of which existed when I first released sodiumoxide. Would like it if those changes were isolated to a single commit and not merged together with unrelated changes.

AppVeyor support would be really nice, I'm not that used to windows development though, so that's why I haven't added it myself.

The PRNG stuff is more scary, but I might be ok with that being hidden behind a feature flag.

**Comment by dbrgn** [comment] 2018-02-15 13:55
I haven't done much with rustfmt so far. @Fraser999 would you be interested in applying your rustfmt config to sodiumoxide? I could implement clippy support in a pull request.

**Comment by Fraser999** [comment] 2018-02-17 18:40
@dbrgn I think @dnaq's hoping for single commit for this, so it'd probably be best if you could just apply it to your PR's commit?  I'd suggest building it into the CI scripts too, since if subsequent commits don't follow the rustfmt style, we can end up needing separate commits just to reapply rustfmt styling.

As for our rustfmt config, we try to keep as close to the defaults as possible.  We only have three non-default options specified in our [rustfmt.toml](https://github.com/Fraser999/rust_sodium/blob/master/rustfmt.toml).  @dnaq may prefer to just use all the rustfmt defaults, in which case there's no need for a rustfmt.toml to be added at all.

There are maybe a couple of possible reasons to hang fire with doing this just now though.  The Rust guys are [bringing rustfmt into the "official" fold](https://blog.rust-lang.org/2018/02/15/Rust-1.24.html), but it's not quite there yet, so we'd probably just end up changing at least how we're running it in the CI scripts.

The other niggle is that running it on Windows causes it to fail when trying to resolve [this path](https://github.com/dnaq/sodiumoxide/blob/master/src/crypto/onetimeauth/mod.rs#L31).  I think it's likely due to [this rustfmt bug](https://github.com/rust-lang-nursery/rustfmt/issues/2407).

If you do want to try adding the rustfmt changes to your PR and want a hand, feel free to email me to avoid cluttering up this thread if you prefer.

**Comment by dnaq** [comment] 2018-05-05 21:36
Please see #203

**Comment by kpp** [comment] 2018-06-28 10:33
One more thing about bindgen and cross-platformness: do we really have to regenerate the bindings in the build script? I would prefer the bindings to be commited in the repo and be touched as the less often as possible.

**Comment by nvesely** [comment] 2018-06-29 03:28
> Hi @dnaq @darrenldl @Dylan-DPC @kinggoesgaming @nvesely @samscott89

You can use @sodiumoxide/owners.

> 1. Rather than supporting any version of libsodium to be linked, I plunked for encouraging usage of a pinned version of libsodium.

Yes, I had this on my todo list. I just opened #231.

> use pkg-config, but warn if the installed version isn't the pinned version.

`pkg-config` doesn't support `no_std`, but we might be able to work around that with libcore or another `no_std` compatible helper crate.

As far as the bindgen issue goes, I do think we need to improve the testing situation of this crate drastically, including ideally testing on the 3 major desktop and 2 major mobile platforms. I do like the use of bindgen and I think if further issues are encountered, we should try to fix them upstream (in addition to confirming the issues you listed are not presently affecting the crate). We might also need to update our documentation.

Thanks for chiming in :smiley_cat:

**Comment by kpp** [comment] 2020-11-28 11:52
We integrated almost all features from rust_sodium including static linkage, downloading packages and many more. Also we fixed several issues in build.rs so our fork is more robust.

Feel free to reopen issue if you think we are missing something.

**Closed by kpp** 2020-11-28 11:52 UTC
